server:
  port: 8501
# 自定义配置  编写一个配置类来获取这些数据
elite:
  auth:
    noAuthUrls:
      - /admin/system/index/login
      - /admin/system/index/generateValidateCode
# 自定义配置 编写一个配置类获取关于minio仓库的信息
#  minio:
#    endpoint: http://192.168.238.128:9000
#    accessKey: admin
#    secretKey: admin123456
#    bucketName: elite-image
#    create-bucket: true
  minio:
    endpoint: http://127.0.0.1:9000
    accessKey: minioadmin
    secretKey: minioadmin
    bucketName: elite-image

spring:
  # 配置Mysql的连接信息
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.238.128:3306/db_spzx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456


  # 配置Redis相关信息
  data:
    redis:
      host: 192.168.238.128
      port: 6379
      #password: 123456
      jedis:
        pool:
          max-active: 8
          max-idle: 8

# 配置mybatis信息
mybatis:
  mapper-locations: classpath:/mapper/*.xml   # mapper映射文件位置
  configuration:
   # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true  # 开启驼峰

# page helper 配置
pagehelper:
  helper-dialect: mysql  # sql语言辅助器
  reasonable: true # 配置分页参数合理化功能
  support-methods-arguments: true #支持通过Mapper接口参数来传递分页参数 默认false
  params: count=countSql