server:
  port: 8511

spring:
  application:
    name: service-product
  cloud:
    # nacos配置
    nacos:
      discovery:
        server-addr: 192.168.238.128:8848

  # Mysql配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.238.128:3306/db_spzx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

# mybatis配置
mybatis:
  mapper-locations: classpath:/mapper/*.xml   # mapper映射文件位置
  configuration:
    # log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true  # 开启驼峰

# page helper 配置
pagehelper:
  helper-dialect: mysql  # sql语言辅助器
  reasonable: true # 配置分页参数合理化功能
  support-methods-arguments: true #支持通过Mapper接口参数来传递分页参数 默认false
  params: count=countSql